const styles = {
    container: {
        minHeight: '100vh',
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    },
    layout: {
        display: 'flex',
        minHeight: '100vh',
    },
    sidebar: {
        width: '280px',
        background: 'linear-gradient(180deg, #1a1f36 0%, #0f1419 100%)',
        color: 'white',
        display: 'flex',
        flexDirection: 'column',
        boxShadow: '4px 0 24px rgba(0,0,0,0.3)',
        position: 'fixed',
        height: '100vh',
        left: 0,
        top: 0,
        zIndex: 100,
    },
    sidebarHeader: {
        padding: '24px',
        background: 'rgba(255,255,255,0.05)',
        borderBottom: '1px solid rgba(255,255,255,0.1)',
    },
    logo: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        fontSize: '24px',
        fontWeight: '700',
        marginBottom: '8px',
    },
    roleChip: {
        display: 'inline-block',
        padding: '4px 12px',
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        borderRadius: '12px',
        fontSize: '11px',
        fontWeight: '600',
        textTransform: 'uppercase',
        letterSpacing: '0.5px'
    },
    nav: {
        flex: 1,
        padding: '24px 16px',
        overflowY: 'auto',
    },
    navSection: {
        marginBottom: '32px',
    },
    navTitle: {
        fontSize: '11px',
        fontWeight: '700',
        color: '#8b92a7',
        textTransform: 'uppercase',
        letterSpacing: '1px',
        marginBottom: '12px',
        paddingLeft: '12px',
    },
    navItem: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        padding: '12px 16px',
        borderRadius: '8px',
        color: '#cbd5e1',
        textDecoration: 'none',
        fontSize: '14px',
        fontWeight: '500',
        transition: 'all 0.2s',
        cursor: 'pointer',
        marginBottom: '4px',
    },
    navItemActive: {
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        color: 'white',
        transform: 'translateX(4px)',
        boxShadow: '0 4px 12px rgba(102, 126, 234, 0.4)',
    },
    sidebarFooter: {
        padding: '20px',
        background: 'rgba(255,255,255,0.03)',
        borderTop: '1px solid rgba(255,255,255,0.1)',
    },
    userProfile: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
    },
    avatar: {
        width: '40px',
        height: '40px',
        borderRadius: '50%',
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '16px',
        fontWeight: '700',
    },
    mainContent: {
        flex: 1,
        marginLeft: '280px',
        padding: '32px',
        minHeight: '100vh',
    },
    card: {
        background: 'white',
        borderRadius: '16px',
        padding: '24px',
        boxShadow: '0 4px 24px rgba(0,0,0,0.08)',
        marginBottom: '24px',
    },
    cardHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '24px',
        paddingBottom: '16px',
        borderBottom: '2px solid #f1f5f9',
    },
    statsGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
        gap: '20px',
        marginBottom: '32px',
    },
    statCard: {
        background: 'white',
        borderRadius: '16px',
        padding: '24px',
        boxShadow: '0 4px 16px rgba(0,0,0,0.06)',
        border: '2px solid #f1f5f9',
        transition: 'all 0.3s',
    },
    statCardHover: {
        transform: 'translateY(-4px)',
        boxShadow: '0 8px 24px rgba(0,0,0,0.12)',
    },
    btn: {
        padding: '12px 24px',
        borderRadius: '8px',
        border: 'none',
        fontWeight: '600',
        fontSize: '14px',
        cursor: 'pointer',
        transition: 'all 0.2s',
        display: 'inline-flex',
        alignItems: 'center',
        gap: '8px',
    },
    btnPrimary: {
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        color: 'white',
        boxShadow: '0 4px 12px rgba(102, 126, 234, 0.3)',
    },
    btnSecondary: {
        background: '#f1f5f9',
        color: '#475569',
    },
    btnSuccess: {
        background: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
        color: 'white',
    },
    btnDanger: {
        background: 'linear-gradient(135deg, #ef4444 0%, #dc2626 100%)',
        color: 'white',
    },
    badge: {
        display: 'inline-block',
        padding: '4px 12px',
        borderRadius: '12px',
        fontSize: '12px',
        fontWeight: '600',
    },
    badgeSuccess: {
        background: '#d1fae5',
        color: '#065f46',
    },
    badgeWarning: {
        background: '#fef3c7',
        color: '#92400e',
    },
    badgeDanger: {
        background: '#fee2e2',
        color: '#991b1b',
    },
    badgeInfo: {
        background: '#dbeafe',
        color: '#1e40af',
    },
    table: {
        width: '100%',
        borderCollapse: 'collapse',
    },
    th: {
        textAlign: 'left',
        padding: '12px',
        borderBottom: '2px solid #e2e8f0',
        fontWeight: '600',
        color: '#475569',
        fontSize: '13px',
    },
    td: {
        padding: '16px 12px',
        borderBottom: '1px solid #f1f5f9',
        fontSize: '14px',
        color: '#334155',
        fontWeight : '500',
    },
    authContainer: {
        minHeight: '100vh',
        width: '100%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '20px',
        boxSizing: 'border-box',
    },
    authCard: {
        background: 'white',
        borderRadius: '20px',
        padding: '40px',
        width: '100%',
        maxWidth: '440px',
        boxShadow: '0 20px 60px rgba(0,0,0,0.15)',
    },
    input: {
        width: '100%',
        padding: '14px',
        borderRadius: '8px',
        border: '2px solid #e2e8f0',
        fontSize: '14px',
        transition: 'all 0.2s',
        marginTop: '8px',
        boxSizing: 'border-box',
    },
    formGroup: {
        marginBottom: '20px',
    },
    label: {
        display: 'block',
        marginBottom: '4px',
        fontWeight: '600',
        fontSize: '13px',
        color: '#475569',
    },
};

export default styles;